name: CI/CD Express with Docker Compose

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version for the release'
        required: true

jobs:
  lint:
    name: Linting Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier Check
        run: npx prettier --check --write .

      - name: Run ESLint
        run: npm run lint

  build-and-publish:
    name: Build and Push Docker Image
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set output release tag
        id: release
        if: github.event_name == 'release'
        run: |
          echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Set output release tag (manual dispatch)
        id: dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "RELEASE_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          if [ -z "$RELEASE_VERSION" ]; then
            echo "RELEASE_VERSION=main" >> $GITHUB_ENV
          fi
          RELEASE_VERSION="${RELEASE_VERSION#?}"
          echo "Building Docker image with tag: $RELEASE_VERSION"
          docker build --pull --no-cache . -t ghcr.io/${{ github.repository }}:$RELEASE_VERSION -t ghcr.io/${{ github.repository }}:latest
          echo "Pushing Docker image with tag: $RELEASE_VERSION"
          docker push ghcr.io/${{ github.repository }}:$RELEASE_VERSION
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    name: Deploy via SSH
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GIT_TOKEN }}
            echo "Removing old images latest..."
            echo "Cleaning up old Docker images..."
            docker system prune -af || true
            cd project/practice-deploy-be
            git pull origin main
            docker compose down --remove-orphans || true
            echo "Setting environment variables..."
            [[ -z "${{ secrets.POSTGRES_DB }}" ]] && echo "POSTGRES_DB is empty!"
            [[ -z "${{ secrets.POSTGRES_USER }}" ]] && echo "POSTGRES_USER is empty!"
            [[ -z "${{ secrets.POSTGRES_PASSWORD }}" ]] && echo "POSTGRES_PASSWORD is empty!"
            [[ -z "${{ secrets.DATABASE_URL }}" ]] && echo "DATABASE_URL is empty!"
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export RELEASE_VERSION_ENV=$RELEASE_VERSION
            # Debugging: Print values
            echo "POSTGRES_DB: $POSTGRES_DB"
            echo "POSTGRES_USER: $POSTGRES_USER"
            echo "POSTGRES_PASSWORD: $POSTGRES_PASSWORD"
            echo "DATABASE_URL: $DATABASE_URL"
            echo "RELEASE_VERSION_ENV: $RELEASE_VERSION_ENV"
            POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            DATABASE_URL=${{ secrets.DATABASE_URL }} \
            docker compose up -d
